# version: '3'
# services:
#   app:
#     image: 'chishin/nginx-proxy-manager-zh:release'
#     restart: always
#     ports:
#       - '8000:80'
#       - '8100:81'
#       - '44300:443'
#     volumes:
#       - ./data:/data
#       - ./letsencrypt:/etc/letsencrypt

services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt