name: Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # 自动增加版本号
      - name: Bump version
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          minor-wording: 'feat,feature'
          major-wording: 'MAJOR,major'
          patch-wording: 'fix,patch,chore,refactor'
          rc-wording: 'RELEASE,alpha'
          default: patch
          commit-message: 'CI: 版本号更新到 {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 登录 ACR
      - name: Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t ${{ secrets.ACR_REGISTRY }}/beng003_docker/dagscheduler-backend:${{ steps.version-bump.outputs.newTag }} .

      # 推送 Docker 镜像
      - name: Push Docker image
        run: docker push ${{ secrets.ACR_REGISTRY }}/beng003_docker/dagscheduler-backend:${{ steps.version-bump.outputs.newTag }}